### ISSUE TITLE
Local vs UTM Coordinates

### ISSUE THREAD

**Issue by mpalmsten** [Coastal-Imaging-Research-Network/Shoreline-Mapping-Toolbox#1]
Hi @mitchharley! 

Thanks for posting the shoreline mapping toolbox. We are attempting to use it to look at shorelines in FL. I am wondering how you made the decision to use UTM coordinates vs local (argus coordinates). We've been working in local coordinates and are trying to decide on the merits of switching to UTM to get it to run for us (vs editing the code to work in local coords).

Thanks,
Meg

**Comment by mitchharley** [comment]
Hi Meg,

Unless I misunderstood something, I don't think it matters what coordinate system you are in, just as long as the transects file that seeds the algorithm is in the same coordinate system. Best of luck!

Cheers,
Mitch

**Comment by sivaiahborra** [comment]
Dear @mitchharley,
I have timex image which are in local coordinates in meters. I want to apply your shoreline mapping code to pick shoreline from my timex images, Can you let me know how to start with it and get the shoreline ? only timex image is enough or anything else is required run the code/functions

Thank you for your time.
